"""Single source of truth for model feature / target column names.

Two tables exist:
  * the REAL table  (data/processed/train_real.parquet): CPCB measurements + Sentinel-2 reflectance
  * the SYNTHETIC demo table (data/processed/train.parquet): generated by scripts/generate_synthetic_train.py

Per-target feature sets (``FEATURE_SETS``)
-------------------------------------------
A single global feature list was replaced by a per-target one after clean ablations (identical rows,
identical spatial-CV folds, same random seed -- unlike the earlier "more data + more features" comparison
that changed both at once) on ``train_real_large.parquet``:

| target     | n rows | best feature set          | Spearman (best)          | effect of context features               |
|------------|--------|----------------------------|---------------------------|--------------------------------------------|
| bod        | 4,684  | spectral + type + season + urban | 0.256 -> 0.350 (+urban)   | urban +0.121 R2; rainfall +0.122 R2 too, but adds nothing on top of urban and is dropped (see RAINFALL_COLS below) |
| do         | 5,571  | spectral only               | best at spectral-only     | +urban R2 -0.074, +rainfall R2 -0.079 -- context features actively hurt DO |
| turbidity  | 2,308  | spectral + type              | best at spectral-only/+type | +urban R2 -0.111, +rainfall R2 -0.158 -- same story |

So DO gets spectral bands only, turbidity adds the water-body-type one-hot (rivers/lakes/reservoirs have a
materially different reflectance-turbidity relationship), and BOD -- the one target where urban proximity is
a real, measured gain -- adds type + season + urban proximity. Rainfall was fetched and validated (see
src.data.weather) but is not in any feature set: in the same clean ablations it never beat urban proximity
alone and added nothing on top of it, so it stays in the parquet as data (for anyone who wants to re-test it)
without being wired into any model.
"""

# Spectral features available for every real visit (water temperature has no in-situ or satellite source here).
# is_river/is_lake/is_reservoir one-hot the CPCB-reported water_body_type ("unknown" is the implicit
# all-zero baseline). Rivers show a materially different, steeper reflectance-turbidity relationship than
# still water (see reports/real/empirical_formula_validation.json), so this lets the tree split on type
# instead of every target being forced through one pooled relationship.
WATER_BODY_TYPES = ("river", "lake", "reservoir")

# DO/BOD are not optically active -- reflectance bands alone cannot see sewage or dissolved oxygen.
# These are non-satellite context features standing in for the two real physical drivers reflectance
# misses: rainfall-driven runoff (src.data.weather) and nearby urban/industrial discharge
# (src.data.city_proximity). "post_monsoon" (Oct-Nov) is the implicit all-zero season baseline.
SEASONS = ("winter", "summer", "monsoon")
# Fetched and validated (src.data.weather); kept as data but wired into no feature set -- see the ablation
# table above. Not a "future work" placeholder: it was tested and dropped.
RAINFALL_COLS = ["rain_3d_mm", "rain_7d_mm", "rain_14d_mm", "rain_30d_mm"]
URBAN_PROXY_COLS = ["dist_nearest_city_km", "urban_load_index"]

SPECTRAL_COLS = ["B2", "B3", "B4", "B5", "B6", "B8", "B11", "ndci", "bdm2", "bdm3", "red_green", "nir"]
TYPE_COLS = ["is_river", "is_lake", "is_reservoir"]
SEASON_COLS = ["is_winter", "is_summer", "is_monsoon"]

# Per-target feature sets (see the module docstring for the evidence). DO is not optically active, so
# context features are actively harmful for it; turbidity gains from knowing the water-body type; BOD is
# the one target where urban proximity is a real, measured gain.
FEATURE_SETS: dict[str, list[str]] = {
    "do": list(SPECTRAL_COLS),
    "turbidity": SPECTRAL_COLS + TYPE_COLS,
    "bod": SPECTRAL_COLS + TYPE_COLS + SEASON_COLS + URBAN_PROXY_COLS,
}

# Kept as the union of every feature set, for callers that still want one flat list (e.g. the WQI-tier
# classifier, which predicts a label derived from all three targets' chemistry). "bod" already contains
# every column any other target set uses.
REAL_FEATURE_COLS = list(FEATURE_SETS["bod"])
REAL_TARGET_COLS = ["do", "bod", "turbidity"]          # real labels; Chl-a has no ground truth

# Synthetic demo table (includes a simulated surface temperature and a simulated Chl-a label).
SYNTH_FEATURE_COLS = ["B2", "B3", "B4", "B5", "B8", "B11", "ndci", "bdm2", "bdm3", "red_green", "nir",
                      "temp_surface"]
SYNTH_TARGET_COLS = ["chl_a", "turbidity", "do"]

# Targets whose distribution is heavy-tailed: modelled on a log1p scale.
LOG_TARGETS = ("bod", "turbidity", "chl_a")

META_COLS = ["site", "water_body_type", "lat", "lon", "date", "sensor"]


def add_water_body_onehot(df):
    """Add is_river/is_lake/is_reservoir boolean columns from ``water_body_type`` (in place semantics avoided: returns df)."""
    for t in WATER_BODY_TYPES:
        df[f"is_{t}"] = (df["water_body_type"] == t).astype(int)
    return df


def add_season_onehot(df):
    """Add is_winter/is_summer/is_monsoon from ``date`` month (Dec-Feb/Mar-May/Jun-Sep; Oct-Nov is baseline)."""
    month = df["date"].dt.month
    df["is_winter"] = month.isin([12, 1, 2]).astype(int)
    df["is_summer"] = month.isin([3, 4, 5]).astype(int)
    df["is_monsoon"] = month.isin([6, 7, 8, 9]).astype(int)
    return df
