"""Single source of truth for model feature / target column names.

Two tables exist:
  * the REAL table  (data/processed/train_real.parquet): CPCB measurements + Sentinel-2 reflectance
  * the SYNTHETIC demo table (data/processed/train.parquet): generated by scripts/generate_synthetic_train.py
"""

# Spectral features available for every real visit (water temperature has no in-situ or satellite source here).
# is_river/is_lake/is_reservoir one-hot the CPCB-reported water_body_type ("unknown" is the implicit
# all-zero baseline). Rivers show a materially different, steeper reflectance-turbidity relationship than
# still water (see reports/real/empirical_formula_validation.json), so this lets the tree split on type
# instead of every target being forced through one pooled relationship.
WATER_BODY_TYPES = ("river", "lake", "reservoir")

# DO/BOD are not optically active -- reflectance bands alone cannot see sewage or dissolved oxygen.
# These are non-satellite context features standing in for the two real physical drivers reflectance
# misses: rainfall-driven runoff (src.data.weather) and nearby urban/industrial discharge
# (src.data.city_proximity). "post_monsoon" (Oct-Nov) is the implicit all-zero season baseline.
SEASONS = ("winter", "summer", "monsoon")
RAINFALL_COLS = ["rain_3d_mm", "rain_7d_mm", "rain_14d_mm", "rain_30d_mm"]
URBAN_PROXY_COLS = ["dist_nearest_city_km", "urban_load_index"]

SPECTRAL_COLS = ["B2", "B3", "B4", "B5", "B6", "B8", "B11", "ndci", "bdm2", "bdm3", "red_green", "nir"]
TYPE_COLS = [f"is_{t}" for t in WATER_BODY_TYPES]
SEASON_COLS = [f"is_{s}" for s in SEASONS]

REAL_TARGET_COLS = ["do", "bod", "turbidity"]          # real labels; Chl-a has no ground truth

# Per-target feature sets, chosen by ablation on train_real_large.parquet -- identical rows (rainfall present,
# n=4,684 / 5,571 / 2,308) and identical site-blocked folds, so these compare features, not sample size.
# A single shared list was measurably wrong: context features help BOD a lot and hurt the other two.
#
#   target     spectral   +type    +season   +urban        +rainfall
#   bod        -0.011     -0.037   -0.025    +0.121 <-best  +0.122   (Spearman 0.256 -> 0.350)
#   do         -0.001     -0.036   -0.032    -0.074         -0.079   (spectral-only is best; still ~0)
#   turbidity  -0.065     -0.071   -0.060    -0.111         -0.158   (spectral-only is best)
#
# RAINFALL_COLS are deliberately in NO feature set: they never helped (+0.001 on BOD) and hurt DO and
# turbidity. They stay in the table as data, and the finding is recorded in data_source_log.md.
FEATURE_SETS = {
    "do": list(SPECTRAL_COLS),
    "turbidity": SPECTRAL_COLS + TYPE_COLS,
    "bod": SPECTRAL_COLS + TYPE_COLS + SEASON_COLS + URBAN_PROXY_COLS,
}

# Union of everything any target uses -- for callers that need one column list (the tier/screening
# classifiers, dropna checks, the dashboard). Not a feature set for any single regression target.
REAL_FEATURE_COLS = SPECTRAL_COLS + TYPE_COLS + SEASON_COLS + URBAN_PROXY_COLS


def features_for(target: str) -> list[str]:
    """Feature columns for one regression target (falls back to the union for unknown targets)."""
    return list(FEATURE_SETS.get(target, REAL_FEATURE_COLS))

# Synthetic demo table (includes a simulated surface temperature and a simulated Chl-a label).
SYNTH_FEATURE_COLS = ["B2", "B3", "B4", "B5", "B8", "B11", "ndci", "bdm2", "bdm3", "red_green", "nir",
                      "temp_surface"]
SYNTH_TARGET_COLS = ["chl_a", "turbidity", "do"]

# Targets whose distribution is heavy-tailed: modelled on a log1p scale.
LOG_TARGETS = ("bod", "turbidity", "chl_a")

META_COLS = ["site", "water_body_type", "lat", "lon", "date", "sensor"]


def add_water_body_onehot(df):
    """Add is_river/is_lake/is_reservoir boolean columns from ``water_body_type`` (in place semantics avoided: returns df)."""
    for t in WATER_BODY_TYPES:
        df[f"is_{t}"] = (df["water_body_type"] == t).astype(int)
    return df


def add_season_onehot(df):
    """Add is_winter/is_summer/is_monsoon from ``date`` month (Dec-Feb/Mar-May/Jun-Sep; Oct-Nov is baseline)."""
    month = df["date"].dt.month
    df["is_winter"] = month.isin([12, 1, 2]).astype(int)
    df["is_summer"] = month.isin([3, 4, 5]).astype(int)
    df["is_monsoon"] = month.isin([6, 7, 8, 9]).astype(int)
    return df
